---


- hosts: all

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat).
      yum: 'name="{{ item }}" state=present'
      with_items:
        - openssh-server
        - openssh-clients
      when: ansible_os_family == 'RedHat'

    - name: Ensure build dependencies are installed (Debian).
      apt: 'name="{{ item }}" state=installed'
      with_items:
        - openssh-server
        - openssh-client
      when: ansible_os_family == 'Debian'

  roles:
    - { role: ../,
        sudoers_enabled: no
      }
