---
language: python
python:
  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
#  - ANSIBLE_VERSION=latest
#  - ANSIBLE_VERSION=2.4.1.0
  - ANSIBLE_VERSION=2.3.1.0
#  - ANSIBLE_VERSION=2.2.2.0  
cache: bundler
#sudo: false
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
#os:
#  - linux
#  - osx
services:
  - docker
install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check ansible version
  - ansible --version

  # Prepare tests
  #- echo localhost > hosts

  # Check syntax
  - ansible-playbook -i hosts --syntax-check eclipse.yml -e "python_versions=[2.7]"

  # First run
  - travis_wait 30 ansible-playbook -i hosts --connection=local --sudo -vvvv eclipse.yml -e "python_versions=[2.7]"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
#  email: false
#  hipchat:
#    rooms:
#      secure: GPUtM44MpgqN/3+TXw4Onp7TpF6YOKpVQkB/sfwGYS1oHUCkp2eb3eGGfJAIUtNxkfFVkdUxM/Bp9GMCnpVjJwRRZP6hYUmlpjCHl8CiK2MjbLvzV65qqBAqYl5bLzKkmmRdPiC31m9ixMe4TiAhJFBK1NoETOP1LkCJ04ezL6U=
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
