---

#language: python
#python: "2.7"

cache: bundler
#sudo: false
sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=2.1.1
#os:
#  - linux
#  - osx

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - sudo ansible --version

  # Prepare tests
  #- echo localhost > hosts

#  - sudo ansible-galaxy install --role-file requirements.yml

  # Check syntax
  - sudo ansible-playbook -i hosts --syntax-check eclipse.yml

  # First run
  - travis_wait 30 sudo ansible-playbook -i hosts --connection=local --sudo -vvvv eclipse.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
#  email: false
#  hipchat:
#    rooms:
#      secure: GPUtM44MpgqN/3+TXw4Onp7TpF6YOKpVQkB/sfwGYS1oHUCkp2eb3eGGfJAIUtNxkfFVkdUxM/Bp9GMCnpVjJwRRZP6hYUmlpjCHl8CiK2MjbLvzV65qqBAqYl5bLzKkmmRdPiC31m9ixMe4TiAhJFBK1NoETOP1LkCJ04ezL6U=
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
