# This file was generated by ansible for albandri-laptop-misys.misys.global.ad
FROM ubuntu:20.04

# Volume can be accessed outside of container
VOLUME [/usr/local/eclipse]

ENV DEBIAN_FRONTEND noninteractive
ENV ECLIPSE_HOME /usr/local/eclipse
ENV WORKDIR /home/vagrant

# Working dir
WORKDIR /home/vagrant

# Install ansible
RUN apt-get -q update &&\
    apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
    git bzip2 zip unzip python-yaml python-jinja2 rsyslog gpg-agent \
    ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo numactl libnuma1 pciutils \
    apt-utils apt-transport-https ca-certificates software-properties-common \
    locales xz-utils ksh wget tzdata sudo curl lsof sshpass \
    systemd systemd-cron \
    python3-setuptools python3 python3-pip python3-dev python3-apt \
    openjdk-8-jdk maven gcc g++ make \
    net-tools iputils-ping x11-apps \
    gnome-keyring gnome-keyring gnupg2 pass \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip==20.0.2 \
    && pip3 install ansible==2.9.7 zabbix-api==0.5.4 docker-compose==1.25.3

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
ENV ANSIBLE_CONFIG=${JENKINS_USER_HOME}/ansible.cfg

# ADD
ADD defaults $WORKDIR/ansible-eclipse/defaults
ADD meta $WORKDIR/ansible-eclipse/meta
ADD files $WORKDIR/ansible-eclipse/files
ADD handlers $WORKDIR/ansible-eclipse/handlers
ADD tasks $WORKDIR/ansible-eclipse/tasks
ADD templates $WORKDIR/ansible-eclipse/templates
#ADD vars $WORKDIR/ansible-eclipse/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD eclipse.yml $WORKDIR/ansible-eclipse/eclipse.yml

# Execute
RUN ansible-playbook $WORKDIR/ansible-eclipse/eclipse.yml -c local \
 -e "python_interpreter=python3" \
 -vvvv

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN chmod +x /usr/local/eclipse/eclipse-4/eclipse

RUN ln -sf /dev/stdout /var/log/eclipse.log
#    && ln -sf /dev/stderr hs_err_pid*.log

#EXPOSE 21:9999
ENTRYPOINT  ["/usr/local/eclipse/eclipse-4/eclipse"]
CMD ["-g", "deamon off;"]
