# This file was generated by ansible for albandri-laptop-misys.misys.global.ad
FROM ubuntu:18.04

# Volume can be accessed outside of container
VOLUME [/usr/local/eclipse]

ENV DEBIAN_FRONTEND noninteractive
ENV ECLIPSE_HOME /usr/local/eclipse
ENV WORKDIR /home/vagrant

# Working dir
WORKDIR /home/vagrant

# Because docker replaces /sbin/init: https://github.com/dotcloud/docker/issues/1024
#RUN dpkg-divert --local --rename --add /sbin/initctl

# Make sure the package repository is up to date.
RUN apt-get clean && apt-get -y update

# Install ansible
RUN apt-get install -y git unzip python-dev python-yaml python-jinja2 python-pip ansible openjdk-8-jdk

# ADD
ADD defaults $WORKDIR/ansible-eclipse/defaults
ADD meta $WORKDIR/ansible-eclipse/meta
ADD files $WORKDIR/ansible-eclipse/files
ADD handlers $WORKDIR/ansible-eclipse/handlers
ADD tasks $WORKDIR/ansible-eclipse/tasks
ADD templates $WORKDIR/ansible-eclipse/templates
#ADD vars $WORKDIR/ansible-eclipse/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD eclipse.yml $WORKDIR/ansible-eclipse/eclipse.yml

# Execute
#RUN pwd
#RUN ls -lrta
#RUN ansible --version
RUN echo localhost > hosts && ansible-playbook $WORKDIR/ansible-eclipse/eclipse.yml -c local -vvvv

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN chmod +x /usr/local/eclipse/eclipse-4/eclipse

RUN ln -sf /dev/stdout /var/log/eclipse.log
#    && ln -sf /dev/stderr hs_err_pid*.log

#EXPOSE 21:9999
ENTRYPOINT  ["/usr/local/eclipse/eclipse-4/eclipse"]
CMD ["-g", "deamon off;"]
