---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: run_command
      action: run_cmd cmd=date
      register: user

    - debug: msg="{{ user.msg }}"

    - debug: msg="Hostname is {{ ansible_hostname }}"

- name: Install eclipse to all nodes
  hosts: localhost
  gather_facts: false
  # become: true

  roles:
    - { role: ./,
        docker_files_enable: false,
        user: "root",
        home: "/root",
        eclipse_dir_tmp: "{{ tempdir.stdout }}",
        eclipse_plugins_emf_enabled: false,
        eclipse_plugins_cdt_enabled: true,
        eclipse_plugins_cmakeed_enabled: true,
        eclipse_plugins_openinterminal_enabled: false,
        eclipse_plugins_protobuf_enabled: false,
        eclipse_plugins_yedit_enabled: false,
        eclipse_plugins_shelled_enabled: false,
        eclipse_plugins_webpageed_enabled: false,
        eclipse_plugins_pydev_enabled: false,
        eclipse_plugins_m2e_enabled: false,
        eclipse_plugins_subclipse_enabled: true,
    }
