---
- hosts: all
  sudo: true
  roles:
    - { role: ./,
        docker_files_enable: yes,
        user: "root",
        home: "/root",
        eclipse_plugins_emf_enabled: no,
        eclipse_plugins_cdt_enabled: yes,
        eclipse_plugins_cmakeed_enabled: yes,
        eclipse_plugins_openinterminal_enabled: no,
        eclipse_plugins_protobuf_enabled: no,
        eclipse_plugins_yedit_enabled: yes,
        eclipse_plugins_shelled_enabled: no,
        eclipse_plugins_webpageed_enabled: no,
        eclipse_plugins_pydev_enabled: no,
        eclipse_plugins_m2e_enabled: yes,
        eclipse_plugins_subclipse_enabled: yes,
      }

#- include: docker/integration-tests.yml
