---
# from galaxy
# ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors

- src: https://github.com/AlbanAndrieu/ansible-administration.git
  name: albanandrieu.administration
  version: master

#- src: https://github.com/AlbanAndrieu/ansible-awstats.git
#  name: albanandrieu.awstats
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-cmake.git
  name: albanandrieu.cmake
  version: master

- src: https://github.com/AlbanAndrieu/ansible-common.git
  name: albanandrieu.ansible_common
  version: master

#- src: https://github.com/AlbanAndrieu/ansible-conky.git
#  name: albanandrieu.conky
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-cpp.git
  name: albanandrieu.cpp
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-css'
#  name: 'albanandrieu.css'
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-dns.git
  name: albanandrieu.ansible_dns
  version: master

#- src: https://github.com/AlbanAndrieu/ansible-dropbox.git
#  name: albanandrieu.dropbox
#  version: master

#- src: https://github.com/AlbanAndrieu/ansible-eclipse.git
#  name: albanandrieu.eclipse
#  version: master
#
#- src: https://github.com/AlbanAndrieu/ansible-evasive.git
#  name: albanandrieu.evasive
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-gcc.git
  name: albanandrieu.gcc
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-grive'
#  name: 'albanandrieu.grive'
#  version: master
#
##TODO
##- src: https://github.com/Stouts/Stouts.hostname
##  version: master
##  name: Stouts.hostname
#
- src: https://github.com/AlbanAndrieu/ansible-hostname.git
  name: albanandrieu.ansible_hostname
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-jboss'
#  name: 'albanandrieu.jboss'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-jdiskreport'
#  name: 'albanandrieu.jdiskreport'
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-jenkins-slave.git
  name: albanandrieu.jenkins_slave
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-jenkins-swarm'
#  name: 'albanandrieu.jenkins-swarm'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-jmeter'
#  name: 'albanandrieu.jmeter'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-logstash-settings'
#  name: 'albanandrieu.logstash-settings'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-mon'
#  name: 'albanandrieu.mon'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-owasp-wte'
#  name: 'albanandrieu.owasp-wte'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-pagespeed'
#  name: 'albanandrieu.pagespeed'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-phpvirtualbox'
#  name: 'albanandrieu.phpvirtualbox'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-private-bower'
#  name: 'albanandrieu.private-bower'
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-scons.git
  name: albanandrieu.scons
  version: master

- src: https://github.com/AlbanAndrieu/ansible-selenium.git
  name: albanandrieu.selenium
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-shell'
#  name: 'albanandrieu.shell'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-solaris'
#  name: 'albanandrieu.solaris'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-squirrel'
#  name: 'albanandrieu.squirrel'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-sublimetext'
#  name: 'albanandrieu.sublimetext'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-subversion'
#  name: 'albanandrieu.subversion'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-synergy'
#  name: 'albanandrieu.synergy'
#  version: master
#
- src: https://github.com/AlbanAndrieu/ansible-tomcat.git
  name: albanandrieu.tomcat
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-visualvm'
#  name: 'albanandrieu.visualvm'
#  version: master
#
#- src: https://github.com/AlbanAndrieu/ansible-web.git
#  name: albanandrieu.web
#  version: master

#- src: https://github.com/AlbanAndrieu/ansible-webmin.git
#  name: albanandrieu.webmin
#  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-workstation'
#  name: 'albanandrieu.workstation'
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-xvbf.git
  name: albanandrieu.xvbf
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-yourkit'
#  name: 'albanandrieu.yourkit'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-zap'
#  name: 'albanandrieu.zap'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-zfs'
#  name: 'albanandrieu.zfs'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-login'
#  name: 'ansible-login'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-newrelic'
#  name: 'newrelic'
#  version: master

- src: https://github.com/AlbanAndrieu/devbox.chrome.git
  name: chrome
  version: master

#- src: 'https://github.com/AlbanAndrieu/Stouts.collectd'
#  name: 'collectd'
#  version: master
#
##- src: 'https://github.com/AlbanAndrieu/ansible-darthwade-wordpress'
##  name: 'darthwade-wordpress'
##  scm: 'git'
##  version: 'master'
##
##- src: 'https://github.com/AlbanAndrieu/ansible-darthwade-wordpress-apache'
##  name: 'darthwade-wordpress-apache'
##  scm: 'git'
##  version: 'master'
#
#- src: 'https://github.com/AlbanAndrieu/docker.ubuntu'
#  name: 'docker'
#  version: master
#
##TODO nor more maintained
##- src: 'https://github.com/AlbanAndrieu/ansible-role-base'
##  name: 'elao-base'
##  scm: 'git'
##  version: 'master'
##
##- src: 'https://github.com/AlbanAndrieu/ansible-role-ruby'
##  name: 'elao-ruby'
##  scm: 'git'
##  version: 'master'
##
##- src: 'https://github.com/AlbanAndrieu/ansible-role-sass'
##  name: 'elao-sass'
##  scm: 'git'
##  version: 'master'
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-apache'
#  name: 'geerlingguy.apache'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-elasticsearch'
#  name: 'geerlingguy.elasticsearch'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-elasticsearch-curator'
#  name: 'geerlingguy.elasticsearch-curator'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-firewall'
#  name: 'geerlingguy.firewall'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-git'
#  name: 'geerlingguy.git'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-kibana'
#  name: 'geerlingguy.kibana'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-logstash'
#  name: 'geerlingguy.logstash'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-mysql'
#  name: 'geerlingguy.mysql'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-nginx'
#  name: 'geerlingguy.nginx'
#  version: master

- src: https://github.com/geerlingguy/ansible-role-ntp.git
  name: geerlingguy.ntp
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-role-php'
#  name: 'geerlingguy.php'
#  version: master
#
#- src: 'https://github.com/geerlingguy/ansible-role-php-mysql'
#  name: 'geerlingguy.php-mysql'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-phpmyadmin'
#  name: 'geerlingguy.phpmyadmin'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-redis'
#  name: 'geerlingguy.redis'
#  version: master
#
- src: https://github.com/geerlingguy/ansible-role-repo-epel.git
  name: geerlingguy.repo-epel
  version: master

- src: https://github.com/geerlingguy/ansible-role-repo-remi.git
  name: geerlingguy.repo-remi
  version: master

#- src: https://github.com/geerlingguy/ansible-role-pip.git
#  name: geerlingguy.pip
#  version: master

- src: https://github.com/geerlingguy/ansible-role-docker.git
  name: geerlingguy.docker
  version: master

#- src: 'https://github.com/geerlingguy/ansible-role-samba'
#  name: 'geerlingguy.samba'
#  version: master
#
##- src: 'https://github.com/AlbanAndrieu/ansible-role-java'
##  name: 'geerlingguy.java'
##  scm: 'git'
##  version: 'master'
#
##- src: 'https://github.com/AlbanAndrieu/oracle-java'
##  name: 'java'
##  scm: 'git'
##  version: 'master'
#
#- src: 'https://github.com/ansiblebit/oracle-java'
#  name: 'ansiblebit.oracle-java'
#  version: master

- src: https://github.com/gantsign/ansible-role-maven.git
  name: maven
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-java-certificate'
#  name: 'java-certificate'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/Stouts.jenkins'
#  name: 'jenkins-master'
#  version: master

#- src: https://github.com/AlbanAndrieu/ansible-locale.git
#  name: locale
#  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-role-maven'
#  name: 'maven'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-role-maven-color'
#  name: 'maven-color'
#  version: master
#
##- src: 'https://github.com/AlbanAndrieu/ansible-monit'
##  name: 'monit'
##  scm: 'git'
##  version: 'master'
#
#- src: 'https://github.com/AlbanAndrieu/ansible-sonatype_nexus'
#  name: 'nexus'
#  version: master

- src: https://github.com/AlbanAndrieu/ansible-nodejs.git
  name: geerlingguy.nodejs
  version: master

- src: https://github.com/Stouts/Stouts.python.git
  name: python
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-role-security'
#  name: 'security'
#  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-sonar'
#  name: 'sonar'
#  version: master

- src: https://github.com/geerlingguy/ansible-role-sonar-runner.git
  name: geerlingguy.sonar-runner
  version: master

#- src: 'https://github.com/AlbanAndrieu/ansible-role-ssl-certs'
#  name: 'ssl-certificate'
#  version: master
#
#- src: https://github.com/andrewrothstein/ansible-trust-ca.git
#  name: ssl-ca-certificate
#  version: master
#
#- src: https://github.com/andrewrothstein/ansible-tls.git
#  name: andrewrothstein.tls
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-supervisor_task'
#  name: 'supervisor'
#  version: master
#
#- src: 'https://github.com/AlbanAndrieu/ansible-vagrant-role'
#  name: 'vagrant'
#  version: master
#
#- src: https://github.com/AlbanAndrieu/ansible-galaxy.ubuntu.virtualbox.git
#  name: albanandrieu.virtualbox
#  version: master
#
#- src: https://github.com/dj-wasabi/ansible-zabbix-agent.git
#  name: dj-wasabi.zabbix-agent
#  version: master

#- src: 'https://github.com/LIP-Computing/ansible-role-nvidia'
#  name: 'opencl'
#  version: master

#- src: https://github.com/elliotweiser/ansible-osx-command-line-tools.git
#  name: elliotweiser.osx-command-line-tools
#  version: master

#- src: https://github.com/geerlingguy/ansible-role-homebrew.git
#  name: geerlingguy.homebrew
#  version: master

#- src: 'https://github.com/geerlingguy/ansible-role-dotfiles'
#  name: 'geerlingguy.dotfiles'
#  version: master
#
#- src: 'https://github.com/geerlingguy/ansible-role-mas'
#  name: 'geerlingguy.mas'
#  version: master
#
##- src: 'https://github.com/geerlingguy/mac-dev-playbook'
##  name: 'mac-dev-playbook'
##  scm: 'git'
##  version: 'master'
#
#- src: https://github.com/AlbanAndrieu/ansible-role-yarn.git
#  name: yarn
#  version: master
#
#- src: 'https://github.com/geerlingguy/ansible-role-nfs'
#  name: 'geerlingguy.nfs'
#  version: master
#
#- src: https://github.com/Oefenweb/ansible-swapfile.git
#  version: master
#  name: ansible-swapfile
#
#- src: 'https://github.com/andrewrothstein/ansible-kubernetes-helm'
#  name: 'andrewrothstein.kubernetes-helm'
#  version: master
#
#- src: 'https://github.com/andrewrothstein/ansible-kubectl'
#  name: 'andrewrothstein.kubectl'
#  version: master

- src: https://github.com/AlbanAndrieu/devbox.chrome.git
  name: chrome
  version: master

#- src: https://github.com/andrewrothstein/ansible-terraform.git
#  name: andrewrothstein.terraform
#  version: master
