
- name:  eclipse | Configure eclipse ini configuration (-Xverify:none)
  lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-Xverify:none'
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (clean)
  lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-clean' insertbefore='-startup'
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (Launcher GTK_version 2)
  replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n{{ eclipse_launcher_XXMaxPermSize }}'
  when: eclipse_launcher_XXMaxPermSize | length > 0
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (Launcher XXMaxPermSize)
#  lineinfile: regexp="(--launcher\.XXMaxPermSize)\n256m" line='\1\n{{ eclipse_launcher_XXMaxPermSize }}' dest={{ eclipse_home }}/eclipse.ini
  replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n{{ eclipse_launcher_XXMaxPermSize }}'
  when: eclipse_launcher_XXMaxPermSize | length > 0
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (XXMaxPermSize)
  lineinfile: regexp="^-XX:MaxPermSize=256m" line="-XX:MaxPermSize={{ eclipse_XXMaxPermSize }}" dest={{ eclipse_home }}/eclipse.ini
  when: eclipse_XXMaxPermSize | length > 0
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (Xms)
  lineinfile: regexp="^-Xms40m" line="-Xms{{ eclipse_Xms }}" dest={{ eclipse_home }}/eclipse.ini
  when: eclipse_Xms | length > 0
  become: true
  
- name:  eclipse | Configure eclipse ini configuration (Xmx)
  lineinfile: regexp="^-Xmx512m" line="-Xmx{{ eclipse_Xmx }}" dest={{ eclipse_home }}/eclipse.ini
  when: eclipse_Xmx | length > 0
  become: true
  
#TODO add
#-Djava.net.preferIPv4Stack=true

#- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='--launcher.GTK_version\n'
