---
# This playbook contains common plays to install eclipse.

- name: Check user exists
  user: name={{eclipse_owner}} state=present

- name: Check user home directory
  stat: path={{eclipse_owner_home}}
  register: home_present

- debug: msg="Path exists and is a directory"
  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

- name: Download eclipse
  get_url:
    url="{{eclipse_url}}"
    dest="/tmp/{{eclipse_archive}}"
  register: eclipse_download
  tags: eclipse_setup

- name: Create base directory
  file:
    dest="{{eclipse_base_dir}}/eclipse-{{eclipse_name}}"
    state=directory
    owner="{{eclipse_owner}}"
    group="{{eclipse_group}}"
  when: eclipse_download.changed
  tags: eclipse_setup

#- name: Extract archive eclipse
#  unarchive:
#    src="/tmp/{{eclipse_archive}}"
#    dest="{{eclipse_base_dir}}"
#    owner="{{eclipse_owner}}"
#    group="{{eclipse_group}}"
#    copy=no
#  sudo_user: "{{eclipse_owner}}"
#  tags: eclipse_setup

#- name: Move {{eclipse_base_dir}}/{{eclipse_archive_extracted}} to {{eclipse_base_dir}}/eclipse-{{eclipse_name}}
#  command: mv {{eclipse_base_dir}}/{{eclipse_archive_extracted}} {{eclipse_base_dir}}/eclipse-{{eclipse_name}}
#  when: eclipse_archive_extracted_present.stat.exists

- name: Extract archive eclipse
  command: tar xzf /tmp/{{eclipse_archive}} -C {{eclipse_base_dir}}/eclipse-{{eclipse_name}} --strip-components=1
  when: eclipse_download.changed

- name: Change archive eclipse ownership
  file: path={{eclipse_base_dir}}/eclipse-{{eclipse_name}} owner={{eclipse_owner}} group={{eclipse_group}} state=directory recurse=yes
  when: eclipse_download.changed

#copy: src=~test/a dest=~test/a owner=root group=root

- name: stat {{eclipse_base_dir}}/eclipse-{{eclipse_name}}
  stat: path={{eclipse_base_dir}}/eclipse-{{eclipse_name}}
  register: eclipse_archive_extracted_present

- debug: msg="Path exists and is a directory"
  when: eclipse_archive_extracted_present.stat.isdir is defined and eclipse_archive_extracted_present.stat.isdir == true

- fail: msg="Whoops! file ownership has changed"
  when: eclipse_archive_extracted_present.stat.pw_name != '{{eclipse_owner}}'

- name: create a link to eclipse
  file:
    src="{{eclipse_base_dir}}/eclipse-{{eclipse_name}}"
    dest="{{eclipse_base_dir}}/eclipse-{{eclipse_major}}"
    state=link
    owner="{{eclipse_owner}}"
    group="{{eclipse_group}}"
  tags: eclipse_setup

- name: Install eclipse MoDisco & EMF Facet plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
    -application org.eclipse.equinox.p2.director \
    -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
    -repository \
    http://download.eclipse.org/releases/{{eclipse_name}}/,\
    http://download.eclipse.org/tools/orbit/downloads/drops/S20110515001817/repository/,\
    http://download.eclipse.org/technology/swtbot/helios/dev-build/update-site,\
    http://eclipse-cs.sf.net/update/,\
    jar:file:org.eclipse.releng.tools-3.7M7.zip \
    -installIU \
    org.eclipse.birt.feature.group,\
    org.eclipse.mylyn.wikitext_feature.feature.group,\
    org.eclipse.acceleo.sdk.feature.group,\
    org.eclipse.m2m.atl.sdk.feature.group,\
    org.eclipse.emf.cdo.sdk.feature.group,\
    org.eclipse.emf.ecoretools.sdk.feature.group,\
    org.eclipse.emf.sdk.feature.group,\
    org.eclipse.emf.compare.sdk.feature.group,\
    org.eclipse.emf.query.sdk.feature.group,\
    org.eclipse.emf.validation.sdk.feature.group,\
    org.eclipse.jet.sdk.feature.group,\
    org.eclipse.net4j.sdk.feature.group,\
    org.eclipse.ocl.all.sdk.feature.group,\
    org.eclipse.m2m.qvt.oml.sdk.feature.group,\
    org.eclipse.uml2.sdk.feature.group,\
    org.antlr.runtime,\
    org.apache.derby,\
    org.apache.derby.source,\
    org.apache.log4j,\
    org.apache.log4j.source,\
    org.apache.commons.lang,\
    org.apache.commons.lang.source,\
    org.apache.commons.jxpath,\
    org.apache.commons.jxpath.source,\
    net.sourceforge.nattable.core,\
    net.sourceforge.nattable.core.source,\
    org.prefuse,\
    org.prefuse.source,\
    org.eclipse.releng.tools.feature.group,\
    org.eclipse.swtbot.eclipse.feature.group,\
    org.eclipse.swtbot.feature.group,\
    net.sf.eclipsecs.feature.group"
  when: eclipse_plugins_emf_enabled and eclipse_plugins_enabled

- name: Install eclipse CDT plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://download.eclipse.org/tools/cdt/releases/helios/ \
  -installIU org.eclipse.cdt.feature.group \
  -installIU org.eclipse.cdt.sdk.feature.group \
  -installIU org.eclipse.cdt.platform.feature.group \
  -installIU org.eclipse.cdt.debug.ui.memory.feature.group \
  -installIU org.eclipse.cdt.debug.edc.feature.group \
  -installIU org.eclipse.cdt.util.feature.group"
  when: eclipse_plugins_cdt_enabled and eclipse_plugins_enabled
  ignore_errors: True

#cmakeed - CMake editor
- name: Install eclipse CMake editor plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://cmakeed.sourceforge.net/eclipse/ \
  -installIU com.cthing.cmakeed.feature.feature.group"
  when: eclipse_plugins_cmakeed_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#OpenInTerminal - Add option in context menu
- name: Install eclipse Open In Terminal plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://eclipse-openinterminal.googlecode.com/svn/trunk/site/ \
  -installIU OpenInTerminal.feature.group"
  when: eclipse_plugins_openinterminal_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#protobuf-dt - Google Protobuffer editor
- name: Install eclipse Proto buffer plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/,http://protobuf-dt.googlecode.com/git/update-site \
  -installIU com.google.eclipse.protobuf.feature.group"
  when: eclipse_plugins_protobuf_enabled and eclipse_plugins_enabled

#yedit - YAML Editor
- name: Install eclipse YAML Editor plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://dadacoalition.org/yedit \
  -installIU org.dadacoalition.yedit.feature.group"
  when: eclipse_plugins_yedit_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#shelled - Bash Script Editor
- name: Install eclipse Bash Script Editor plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
  -installIU net.sourceforge.shelled.feature.group"
  when: eclipse_plugins_shelled_enabled and eclipse_plugins_enabled
  ignore_errors: True
  ignore_errors: True
    
#Web Page Editor
- name: Install eclipse Web Page Editor plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
  -installIU org.eclipse.jst.webpageeditor.feature.feature.group"
  when: eclipse_plugins_webpageed_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#Pydev  
- name: Install python pexpect for adding Pydev certificat
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian'
  with_items:
    - pexpect
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled

#todo for RehHat : sudo yum install pexpect.noarch

- name: Transfer eclipse Pydev certificate
  copy: src=add_pydev_certificate.py dest=/tmp mode=0777 force=yes owner="{{eclipse_owner}}" group="{{eclipse_group}}"
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  
- name: Add eclipse Pydev certificate
  command: python /tmp/add_pydev_certificate.py
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled           

- name: Install eclipse Pydev plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/technology/dltk/updates/,http://pydev.org/updates/ \
  -installIU org.python.pydev.feature.feature.group"
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#Subclipse  
- name: Install JavaHL for subclipse
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian'
  with_items:
    - libsvn-java
  when: eclipse_plugins_subclipse_enabled and eclipse_plugins_enabled

- name: Install eclipse m2e plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://subclipse.tigris.org/update_1.10.x \
  -installIU org.tigris.subversion.subclipse.feature.group \
  -installIU org.tigris.subversion.clientadapter.feature.feature.group \
  -installIU org.tigris.subversion.clientadapter.svnkit.feature.feature.group \
  -installIU org.tigris.subversion.clientadapter.javahl.feature.feature.group \
  -installIU org.tigris.subversion.subclipse.graph.feature.feature.group"
  when: eclipse_plugins_subclipse_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
#Maven m2e
- name: Install eclipse m2e plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{eclipse_base_dir}}/eclipse-{{eclipse_major}} \
  -repository http://download.eclipse.org/releases/{{eclipse_name}}/,http://download.eclipse.org/technology/m2e/releases/1.5/1.5.0.20140606-0033 \
  -installIU org.eclipse.m2e.feature.feature.group,org.eclipse.m2e.logback.feature.feature.group"
  when: eclipse_plugins_m2e_enabled and eclipse_plugins_enabled
  ignore_errors: True
  
- debug: msg="Start eclipse {{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse"
