---
# This playbook contains common plays to install eclipse.

- name: eclipse | Check user exists
  user: name={{ eclipse_owner }} state=present

- name: eclipse | Check user home directory
  stat: path={{ eclipse_owner_home }}
  register: home_present

- debug: msg=" eclipse | Path exists and is a directory"
  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

- name: eclipse | Create temporary directory
  tempfile:
    state: directory
    suffix: staging
#    path: "{{ lookup('env', 'HOME') }}"
  register: tempdir
  connection: local
  changed_when: false
  become: true
  tags: eclipse_setup

- set_fact: eclipse_dir_tmp="{{ tempdir.stdout }}"  | "/tmp"

- include: install_{{ ansible_distribution }}.yml

- debug: var=eclipse_home
- debug: var=eclipse

- name: eclipse | Create a link to eclipse (1)
  file:
    src="{{ eclipse_home }}"
    dest="{{ eclipse_base_dir }}/eclipse-{{ eclipse_major }}"
    state=link
    owner="{{ eclipse_owner }}"
#    group="{{eclipse_group}}"
  become: true
  when: eclipse_download.changed

- name: eclipse | Create a link to eclipse (2)
  file:
    src="{{ eclipse_home }}"
    dest="{{ eclipse_link_base_dir }}/eclipse-{{ eclipse_major }}"
    state=link
    owner="{{ eclipse_owner }}"
#    group="{{eclipse_group}}"
  become: true
  tags: eclipse_setup

- name: eclipse | Create a link to eclipse (3)
  file:
    src="{{ eclipse }}"
    dest="/usr/local/bin/eclipse"
    state=link
    owner="{{ eclipse_owner }}"
    mode=0755
  become: true
  tags: eclipse_setup

- include: cleanups.yml

- include: lombok.yml

- include: config.yml
  when: eclipse_ini_enabled

- name: eclipse | Install eclipse MoDisco & EMF Facet plugins
  command: "{{ eclipse }} -nosplash \
    -application org.eclipse.equinox.p2.director \
    -destination {{ eclipse_home }} \
    -repository \
    http://download.eclipse.org/releases/{{ eclipse_name }}/,\
    http://download.eclipse.org/tools/orbit/downloads/drops/S20110515001817/repository/,\
    http://download.eclipse.org/technology/swtbot/helios/dev-build/update-site,\
    http://eclipse-cs.sf.net/update/,\
    jar:file:org.eclipse.releng.tools-3.7M7.zip \
    -installIU \
    org.eclipse.birt.feature.group,\
    org.eclipse.mylyn.wikitext_feature.feature.group,\
    org.eclipse.acceleo.sdk.feature.group,\
    org.eclipse.m2m.atl.sdk.feature.group,\
    org.eclipse.emf.cdo.sdk.feature.group,\
    org.eclipse.emf.ecoretools.sdk.feature.group,\
    org.eclipse.emf.sdk.feature.group,\
    org.eclipse.emf.compare.sdk.feature.group,\
    org.eclipse.emf.query.sdk.feature.group,\
    org.eclipse.emf.validation.sdk.feature.group,\
    org.eclipse.jet.sdk.feature.group,\
    org.eclipse.net4j.sdk.feature.group,\
    org.eclipse.ocl.all.sdk.feature.group,\
    org.eclipse.m2m.qvt.oml.sdk.feature.group,\
    org.eclipse.uml2.sdk.feature.group,\
    org.antlr.runtime,\
    org.apache.derby,\
    org.apache.derby.source,\
    org.apache.log4j,\
    org.apache.log4j.source,\
    org.apache.commons.lang,\
    org.apache.commons.lang.source,\
    org.apache.commons.jxpath,\
    org.apache.commons.jxpath.source,\
    net.sourceforge.nattable.core,\
    net.sourceforge.nattable.core.source,\
    org.prefuse,\
    org.prefuse.source,\
    org.eclipse.releng.tools.feature.group,\
    org.eclipse.swtbot.eclipse.feature.group,\
    org.eclipse.swtbot.feature.group,\
    net.sf.eclipsecs.feature.group"
  when: eclipse_plugins_emf_enabled and eclipse_plugins_enabled

#TODO failed
- name: eclipse | Install eclipse CDT plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/tools/cdt/releases/helios/ \
  -installIU org.eclipse.cdt.feature.group \
  -installIU org.eclipse.cdt.sdk.feature.group \
  -installIU org.eclipse.cdt.platform.feature.group \
  -installIU org.eclipse.cdt.debug.ui.memory.feature.group \
  -installIU org.eclipse.cdt.debug.edc.feature.group \
  -installIU org.eclipse.cdt.util.feature.group"
  when: eclipse_plugins_cdt_enabled and eclipse_plugins_enabled
  ignore_errors: true

#cmakeed - CMake editor
- name: eclipse | Install eclipse CMake editor plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://cmakeed.sourceforge.net/eclipse/ \
  -installIU com.cthing.cmakeed.feature.feature.group"
  when: eclipse_plugins_cmakeed_enabled and eclipse_plugins_enabled
  ignore_errors: true

#OpenInTerminal - Add option in context menu
- name: eclipse | Install eclipse Open In Terminal plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://eclipse-openinterminal.googlecode.com/svn/trunk/site/ \
  -installIU OpenInTerminal.feature.group"
  when: eclipse_plugins_openinterminal_enabled and eclipse_plugins_enabled
  ignore_errors: true

#protobuf-dt - Google Protobuffer editor
- name: eclipse | Install eclipse Proto buffer plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/,http://protobuf-dt.googlecode.com/git/update-site \
  -installIU com.google.eclipse.protobuf.feature.group"
  when: eclipse_plugins_protobuf_enabled and eclipse_plugins_enabled

#yedit - YAML Editor
- name: eclipse | Install eclipse YAML Editor plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://dadacoalition.org/yedit \
  -installIU org.dadacoalition.yedit.feature.group"
  when: eclipse_plugins_yedit_enabled and eclipse_plugins_enabled
  ignore_errors: true

#shelled - Bash Script Editor
- name: eclipse | Install eclipse Bash Script Editor plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
  -installIU net.sourceforge.shelled.feature.group"
  when: eclipse_plugins_shelled_enabled and eclipse_plugins_enabled
  ignore_errors: true

#Web Page Editor
#- name: eclipse | Install eclipse Web Page Editor plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
#  -installIU org.eclipse.jst.webpageeditor.feature.feature.group"
#  when: eclipse_plugins_webpageed_enabled and eclipse_plugins_enabled
#  ignore_errors: true

#Pydev
- name: eclipse | Install python pexpect for adding Pydev certificat (apt)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' and eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  with_items:
    - python-pexpect

- name: eclipse | Install python pexpect for adding Pydev certificat (yum)
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS' and eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  with_items:
    - pexpect

- name: eclipse | Transfer eclipse Pydev certificate
  copy: src=add_pydev_certificate.py dest={{ eclipse_dir_tmp }} mode=0777 force=yes owner={{ eclipse_owner }} group={{ eclipse_group }}
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: eclipse | Add eclipse Pydev certificate
  command: python {{ eclipse_dir_tmp }}/add_pydev_certificate.py
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: eclipse | Install eclipse Pydev plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/technology/dltk/updates/,http://pydev.org/updates/ \
  -installIU org.python.pydev.feature.feature.group"
  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
  ignore_errors: true

#Subclipse
- name: eclipse | Install JavaHL for subclipse (apt)
  apt: pkg={{ item }} state=present
  become: true
  when: ansible_distribution == 'Debian' and eclipse_plugins_subclipse_enabled and eclipse_plugins_enabled
  with_items:
    - libsvn-java

- name: eclipse | Install JavaHL for subclipse (yum)
  yum: name={{ item }} state=present
  become: true
  when: ansible_distribution == 'CentOS' and eclipse_plugins_subclipse_enabled and eclipse_plugins_enabled
  with_items:
    - subversion-javahl

- name: eclipse | Install eclipse Subversion plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://subclipse.tigris.org/update_1.10.x \
  -installIU org.tigris.subversion.subclipse.feature.group \
  -installIU org.tigris.subversion.clientadapter.feature.feature.group \
  -installIU org.tigris.subversion.clientadapter.svnkit.feature.feature.group \
  -installIU org.tigris.subversion.clientadapter.javahl.feature.feature.group \
  -installIU org.tigris.subversion.subclipse.graph.feature.feature.group"
  when: eclipse_plugins_subclipse_enabled and eclipse_plugins_enabled
  ignore_errors: true

#Maven m2e
- name: eclipse | Install eclipse Maven m2e plugins
  command: "{{ eclipse }} -nosplash \
  -application org.eclipse.equinox.p2.director \
  -destination {{ eclipse_home }} \
  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/technology/m2e/releases/1.5/1.5.0.20140606-0033 \
  -installIU org.eclipse.m2e.feature.feature.group,org.eclipse.m2e.logback.feature.feature.group"
  when: eclipse_plugins_m2e_enabled and eclipse_plugins_enabled
  ignore_errors: true

- include: features.yml

- name: eclipse | fix permissions eclipse home
  file: recurse=yes owner={{ eclipse_owner }} group={{ eclipse_group }} dest={{ eclipse_home }}
  tags: eclipse_setup
  become: true

- name: eclipse | Stat {{ eclipse_home }}
  stat: path={{ eclipse_home }}
  register: eclipse_archive_extracted_present
  become: true

- debug: msg=" eclipse | Path exists and is a directory"
  when: eclipse_archive_extracted_present.stat.isdir is defined and eclipse_archive_extracted_present.stat.isdir == true

- fail: msg=" eclipse | Whoops! file ownership has changed"
  when: eclipse_archive_extracted_present.stat.pw_name != '{{ eclipse_owner }}'

- name: eclipse | Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags: eclipse_setup
  connection: local  
  changed_when: false
#  ignore_errors: "{{ ansible_check_mode }}"
  become: true

- debug: msg=" eclipse | Start eclipse {{ eclipse }}"
