
- set_fact: eclipse_home={{ eclipse_home_dir }}

- set_fact: eclipse="{{ eclipse_home_dir }}/eclipse"

- name: eclipse | Download eclipse on 'master' if we don't have it
  connection: local
  unarchive: src={{ eclipse_url }} dest={{ eclipse_dir_tmp }} copy=no
  register: eclipse_download
  become: true

- name: eclipse | Create base directory
  file:
    dest="{{ eclipse_home }}"
    state=directory
    owner="{{ eclipse_owner }}"
    group="{{ eclipse_group }}"
  become: true
  when: eclipse_download.changed
  tags: eclipse_setup

- name: eclipse | Copy eclipse into place
  copy: src={{ eclipse_dir_tmp }}/eclipse/ dest="{{ eclipse_home }}" owner="{{ eclipse_owner }}" group="{{ eclipse_group }}" 
  #mode=644
  become: true
  tags: eclipse_setup

- name: eclipse | Install tar
  yum: 
    name=tar
    state=present
  tags: eclipse_setup

- name: eclipse | Configure eclipse icon
  template: src=eclipse.desktop.j2 dest={{ eclipse_desktop }}
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
  ignore_errors: yes
  tags: eclipse_setup
