---
dependency:
  name: galaxy
  enabled: false
  options:
    ignore-errors: true
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: eclipse-centos
    image: milcom/centos7-systemd:latest
    groups:
      - group1
    privileged: true
  - name: eclipse-debian-jessie
    image: maint/debian-systemd:latest
    groups:
      - group1
    privileged: true
  - name: eclipse-debian-stretch
    image: minimum2scp/systemd-stretch:latest
    command: /sbin/init
    groups:
      - group1
  - name: eclipse-ubuntu-xenial
    image: solita/ubuntu-systemd:xenial
    groups:
      - group1
    privileged: true
  - name: eclipse-ubuntu-bionic
    image: solita/ubuntu-systemd:bionic
    groups:
      - group1
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # 2 below will be hard to get 100% right
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
