# This file was generated by ansible for {{ansible_fqdn}}
#FROM debian:jessie
FROM ubuntu:16.04

# Volume can be accessed outside of container
VOLUME [{{ docker_volume_directory }}]

MAINTAINER Alban Andrieu "https://github.com/AlbanAndrieu"

ENV DEBIAN_FRONTEND noninteractive
ENV ECLIPSE_HOME {{ eclipse_base_dir }}
ENV WORKDIR /home/vagrant

# Working dir
WORKDIR {{ docker_working_directory }}

# Because docker replaces /sbin/init: https://github.com/dotcloud/docker/issues/1024
#RUN dpkg-divert --local --rename --add /sbin/initctl

# Make sure the package repository is up to date.
RUN apt-get clean && apt-get -y update

# Install ansible
RUN apt-get install -y git unzip python-dev python-yaml python-jinja2 python-pip ansible

# ADD
ADD defaults $WORKDIR/ansible-eclipse/defaults
ADD meta $WORKDIR/ansible-eclipse/meta
ADD files $WORKDIR/ansible-eclipse/files
ADD handlers $WORKDIR/ansible-eclipse/handlers
ADD tasks $WORKDIR/ansible-eclipse/tasks
ADD templates $WORKDIR/ansible-eclipse/templates
#ADD vars $WORKDIR/ansible-eclipse/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD eclipse.yml $WORKDIR/ansible-eclipse/eclipse.yml

# Execute
#RUN pwd
#RUN ls -lrta
#RUN ansible --version
RUN echo localhost > hosts && ansible-playbook $WORKDIR/ansible-eclipse/eclipse.yml -c local -vvvv

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#EXPOSE 21:9999
ENTRYPOINT  ["{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse"]
CMD ["-g", "deamon off;"]
