# {{ ansible_managed }}
#FROM        debian:jessie
#FROM        stackbrew/ubuntu:14.04
FROM        jasongiedymin/ansible-base-ubuntu

# Volume can be accessed outside of container
VOLUME      [{{ docker_volume_directory }}]

MAINTAINER  Alban Andrieu "https://github.com/AlbanAndrieu"

ENV			DEBIAN_FRONTEND noninteractive
ENV         ECLIPSE_HOME {{ eclipse_base_dir }}

# Working dir
WORKDIR {{ docker_working_directory }}

# ADD
ADD defaults $WORKDIR/eclipse/defaults
ADD meta $WORKDIR/eclipse/meta
ADD files $WORKDIR/eclipse/files
ADD handlers $WORKDIR/eclipse/handlers
ADD tasks $WORKDIR/eclipse/tasks
ADD templates $WORKDIR/eclipse/templates
#ADD vars $WORKDIR/eclipse/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD eclipse.yml $WORKDIR/eclipse.yml

# Execute
RUN         pwd
RUN         ls -lrta
RUN         ansible-playbook $WORKDIR/eclipse.yml -c local -vvvv

EXPOSE      22
ENTRYPOINT  ["{{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse"]
CMD ["-g", "deamon off;"]
